version: '3.6'
services:
    db:
        image: postgres:latest
        environment:
            POSTGRES_USER: "${DB_USER}"
            POSTGRES_PASSWORD: "${DB_PASSWORD}"
            POSTGRES_DB: "${DB_NAME}"
        ports:
            - "${DB_PORT}:5432"
        restart: always
        volumes:
            - ./migrations/0001_users.sql:/docker-entrypoint-initdb.d/0001_users.sql

    db-test:
        image: postgres:latest
        environment:
            POSTGRES_USER: "${DB_USER_TEST}"
            POSTGRES_PASSWORD: "${DB_PASSWORD_TEST}"
            POSTGRES_DB: "${DB_NAME_TEST}"
        ports:
            - "${DB_PORT_TEST}:5432"
        restart: always
        volumes:
            - ./migrations/0001_users.sql:/docker-entrypoint-initdb.d/0001_users.sql
            - ./migrations/0002_token.sql:/docker-entrypoint-initdb.d/0002_token.sql           

    pgadmin-compose:
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
            - PGADMIN_DEFAULT_PASSWORD=admin
        ports:
            - '5051:80' 

    redis:
        image: redis:latest
        ports: 
            - '6379:6379'
        restart: always

    web:
        build:
            context: ./
        ports:
            - '8000:8000'  
        depends_on:
            - redis
            - db